
@uri=http://localhost:8000/admin/api/

###
GET {{uri}}upload
###

GET {{uri}}products/60b5edc9597b073474131a02
###

POST {{uri}}categories
Content-Type: application/json


{
  "title": "产品5"
}

###

POST {{uri}}upload
Content-Type: application/json
